### ISSUE TITLE
Feature extraction error: no file named "elements.txt"

### ISSUE THREAD

**Issue by Yutong-Lu** [BenevolentAI/MolBERT#12]
Hi, I was trying to use the pre-trained model to extract features, and I just replaced the pre-trained model file path in the provided script/featurizer.py, but I encountered an error saying there was no elements.txt.

`The following modules were not unloaded:
  (Use "module --force purge" to unload all):

  1) CCconfig         4) imkl/2020.1.217    7) libfabric/1.10.1
  2) gentoo/2020      5) intel/2020.1.217   8) openmpi/4.0.3
  3) gcccore/.9.3.0   6) ucx/1.8.0          9) StdEnv/2020

Due to MODULEPATH changes, the following have been reloaded:
  1) openmpi/4.0.3     2) ucx/1.8.0

The following have been reloaded with a version change:
  1) libfabric/1.15.1 => libfabric/1.10.1

Lmod is automatically replacing "intel/2020.1.217" with "gcc/9.3.0".

Due to MODULEPATH changes, the following have been reloaded:
  1) openmpi/4.0.3     2) ucx/1.8.0

The following have been reloaded with a version change:
  1) libfabric/1.10.1 => libfabric/1.15.1

Traceback (most recent call last):
  File "featurize.py", line 4, in <module>
    f = MolBertFeaturizer(path_to_checkpoint)
  File "/home/yutonglu/molbert/lib/python3.8/site-packages/molbert/utils/featurizer/molbert_featurizer.py", line 61, in __init__
    self.featurizer = self.load_featurizer(config_dict)
  File "/home/yutonglu/molbert/lib/python3.8/site-packages/molbert/utils/featurizer/molbert_featurizer.py", line 176, in load_featurizer
    return SmilesIndexFeaturizer.bert_smiles_index_featurizer(max_seq_len, permute=self.permute)
  File "/home/yutonglu/molbert/lib/python3.8/site-packages/molbert/utils/featurizer/molfeaturizer.py", line 1359, in bert_smiles_index_featurizer
    return cls(
  File "/home/yutonglu/molbert/lib/python3.8/site-packages/molbert/utils/featurizer/molfeaturizer.py", line 1014, in __init__
    self.elements, self.chars = self.load_periodic_table()
  File "/home/yutonglu/molbert/lib/python3.8/site-packages/molbert/utils/featurizer/molfeaturizer.py", line 1062, in load_periodic_table
    df = pd.read_csv(data_path)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/scipy-stack/2022a/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/scipy-stack/2022a/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/scipy-stack/2022a/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/scipy-stack/2022a/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 933, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/scipy-stack/2022a/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1217, in _make_engine
    self.handles = get_handle(  # type: ignore[call-overload]
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/scipy-stack/2022a/lib/python3.8/site-packages/pandas/io/common.py", line 789, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/home/yutonglu/molbert/lib/python3.8/site-packages/molbert/utils/featurizer/../data/elements.txt'`

I could not find the txt file anywhere. Any help would be greatly appreciated!

**Comment by Yutong-Lu** [comment]
I found that the package that I installed somehow did not have the data folder in the utils folder, so I just copied the one in this repo to that directory. Now it works fine.
